ALTER TABLE Implemento DROP CONSTRAINT FK_Implemento_Sede;
ALTER TABLE Implemento ADD CONSTRAINT FK_Implemento_Sede FOREIGN KEY (sede) REFERENCES Sede (nombre) ON DELETE CASCADE;
ALTER TABLE Cancha DROP CONSTRAINT FK_Cancha_Sede;
ALTER TABLE Cancha ADD CONSTRAINT FK_Cancha_Sede FOREIGN KEY (sede) REFERENCES Sede(nombre) ON DELETE CASCADE;



